name: GitHub Pages

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
