name: GitHub Pages

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
